In [21]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import sys          # only needed to determine Python version number

# Set some pandas parameters..
#pd.set_option('display.notebook_repr_html', True)
#pd.set_option('display.max_columns', 10)
#pd.set_option('display.max_rows', 10)

# Matplotlib ptions
import matplotlib.pyplot as plt
import matplotlib   # only needed to determine Matplotlib version number
# Render our plots inline:
%matplotlib inline  
pd.set_option('display.mpl_style', 'default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)

#print('Python version ' + sys.version)
#print('Pandas version ' + pd.__version__)
#print('Matplotlib version ' + matplotlib.__version__)
#pd.show_versions()

In [22]:
scenarios = ['P0-Mi-Ei'] # for quick testing
#scenarios = ['P0-Mh-Ei', 'P1-Mh-Ei', 'P0-Mi-Ei', 'P1-Mi-Ei', 'P0-Me-Ei', 'P1-Me-Ei', 'P0-Mi-E0', 'P1-Mi-E0', 'P0-Mi-E1', 'P1-Mi-E1']
baseIDir = 'output/results'

productData_byscenario = [pd.read_csv(baseIDir+'/productData_'+scenario+'.csv',sep=';',  dtype={'value': np.float64}) for scenario in scenarios]
productDataReg = pd.concat(productData_byscenario)
productDataReg = productDataReg.drop(['Unnamed: 8'],axis=1) # we don't want this column never
#productDataReg['prodLev'] = np.where(productDataReg['prod'] in ['hardWRoundW', 'softWRoundW', 'pulpWFuelW'], 1, 2)
productDataReg['prodLev'] = np.where(productDataReg['prod'].isin(['hardWRoundW', 'softWRoundW', 'pulpWFuelW','ashRoundW']), 'primPr', 'secPr')
productDataReg = productDataReg.drop(['freeDim'],axis=1) # we don't want this column never
productDataReg = productDataReg[productDataReg['parName'] != 'rt'] # we don't want rt in national data
productDataReg.set_index(['scen','country','region','prod','prodLev','year','parName'], inplace=True)
productDataReg=productDataReg.unstack(['parName'])

lagged_productDataReg = productDataReg.groupby(level=['scen','country','region','prod','prodLev']).shift()




productDataReg[90:110]

                                                   value                      \
parName                                               dl        da        dt
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.005935  0.008194  0.014129
                                          2096  0.005936  0.008194  0.014130
                                          2097  0.005937  0.008194  0.014131
                                          2098  0.005937  0.008194  0.014132
                                          2099  0.005938  0.008195  0.014132
                                          2100  0.005938  0.008195  0.014133
                                          2101  0.005938  0.008195  0.014133
                                          2102  0.005938  0.008195  0.014133
                                          2103  0.005938  0.008195  0.014134
                                          2104  0.005938  0.008195  0.014134
                                          2105  0.005939  0.008196  0.014134
                                          2106  0.005939  0.008196  0.014135
                                          2107  0.005939  0.008196  0.014135
                        ashRoundW primPr  2005  0.000303  0.000000  0.000303
                                          2006  0.000303  0.000000  0.000303
                                          2007  0.000534  0.000000  0.000534
                                          2008  0.000587  0.000000  0.000587
                                          2009  0.000646  0.000000  0.000646
                                          2010  0.000711  0.000000  0.000711
                                          2011  0.000782  0.000000  0.000782

                                                                              \
parName                                               dc        sl        sa
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.007402  0.000000  0.000000
                                          2096  0.007403  0.000000  0.000000
                                          2097  0.007403  0.000000  0.000000
                                          2098  0.007403  0.000000  0.000000
                                          2099  0.007404  0.000000  0.000000
                                          2100  0.007404  0.000000  0.000000
                                          2101  0.007404  0.000000  0.000000
                                          2102  0.007404  0.000000  0.000000
                                          2103  0.007404  0.000000  0.000000
                                          2104  0.007405  0.000000  0.000000
                                          2105  0.007405  0.000000  0.000000
                                          2106  0.007405  0.000000  0.000000
                                          2107  0.007405  0.000000  0.000000
                        ashRoundW primPr  2005  0.000000  0.012059  0.002225
                                          2006  0.000000  0.012059  0.002225
                                          2007  0.000000  0.011299  0.002398
                                          2008  0.000000  0.011272  0.002448
                                          2009  0.000000  0.011103  0.001911
                                          2010  0.000000  0.011044  0.002014
                                          2011  0.000000  0.011056  0.002271

                                                                              \
parName                                               st        sc        pl
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  0.000000  609.1190
                                          2096  0.000000  0.000000  609.0390
                                          2097  0.000000  0.000000  608.9810
                                          2098  0.000000  0.000000  608.9430
                                          2099  0.000000  0.000000  608.9200
                                          2100  0.000000  0.000000  608.9070
                                          2101  0.000000  0.000000  608.8990
                                          2102  0.000000  0.000000  608.8950
                                          2103  0.000000  0.000000  608.8910
                                          2104  0.000000  0.000000  608.8870
                                          2105  0.000000  0.000000  608.8820
                                          2106  0.000000  0.000000  608.8580
                                          2107  0.000000  0.000000  608.8250
                        ashRoundW primPr  2005  0.014284  0.005566   91.0000
                                          2006  0.014284  0.004627   91.0000
                                          2007  0.013697  0.004452   83.6508
                                          2008  0.013721  0.004464   82.0893
                                          2009  0.013014  0.004215   81.6309
                                          2010  0.013058  0.004230   79.7861
                                          2011  0.013326  0.004326   77.9309

                                                                             \
parName                                               pc        pw       in
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  1531.430  802.3210  0.00000
                                          2096  1531.360  802.2780  0.00000
                                          2097  1531.320  802.2460  0.00000
                                          2098  1531.290  802.2260  0.00000
                                          2099  1531.270  802.2140  0.00000
                                          2100  1531.260  802.2070  0.00000
                                          2101  1531.250  802.2020  0.00000
                                          2102  1531.250  802.2000  0.00000
                                          2103  1531.240  802.1980  0.00000
                                          2104  1531.240  802.1950  0.00000
                                          2105  1531.240  802.1930  0.00000
                                          2106  1531.220  802.1800  0.00000
                                          2107  1531.190  802.1620  0.00000
                        ashRoundW primPr  2005   229.151   92.0049  0.00000
                                          2006   284.018   92.0049  2.17569
                                          2007   270.467   87.9086  2.26469
                                          2008   267.196   86.9303  2.34426
                                          2009   251.145   81.3394  2.42514
                                          2010   248.375   80.4508  2.50787
                                          2011   249.666   81.0516  2.59147


parName                                            st_or sigma
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  -0.3
                                          2096  0.000000  -0.3
                                          2097  0.000000  -0.3
                                          2098  0.000000  -0.3
                                          2099  0.000000  -0.3
                                          2100  0.000000  -0.3
                                          2101  0.000000  -0.3
                                          2102  0.000000  -0.3
                                          2103  0.000000  -0.3
                                          2104  0.000000  -0.3
                                          2105  0.000000  -0.3
                                          2106  0.000000  -0.3
                                          2107  0.000000  -0.3
                        ashRoundW primPr  2005  0.000000   1.2
                                          2006  0.000000   1.2
                                          2007  0.013697   1.2
                                          2008  0.013721   1.2
                                          2009  0.013014   1.2
                                          2010  0.013058   1.2
                                          2011  0.013326   1.2

## Computing producer and consumer surpluses ##

### Producer surplus ###
$ S_t = S_{t-1} P_{t-1}^{-\sigma} * {\left(  \frac{In_t}{In_{t-1}} \right)}^ {\frac{\gamma}{\sigma} } * P_{t}^{\sigma}  $

$ P_t = P _{t-1} * S_{t-1}^{-\frac{1}{\sigma}}* {\left(  \frac{In_{t-1}}{In_t} \right)}^ {\frac{\gamma}{\sigma} } * S_t^{\frac{1}{\sigma}} $

$ \int P(S) ~ dS = P _{t-1} * S_{t-1}^{-\frac{1}{\sigma}}* {\left(  \frac{In_{t-1}}{In_t} \right)}^ {\frac{\gamma}{\sigma} } * S_{t}^{\frac{\sigma+1}{\sigma}} *  \frac{\sigma}{\sigma+1} $

Producer surplus =  $ P^* * S^* - P _{t-1} * S_{t-1}^{-\frac{1}{\sigma}}* {\left(  \frac{In_{t-1}}{In_t} \right)}^ {\frac{\gamma}{\sigma} } * S^{* ~ \frac{\sigma+1}{\sigma}} *  \frac{\sigma}{\sigma+1}    $

### Consumer surplus ###

$ D_t = D_{t-1} * P_{t-1}^{-\sigma}*P_t^\sigma$

$P_t = P_{t-1} * D_{t-1}^{-\frac{1}{\sigma}} * D_t^\frac{1}{\sigma} $

$ \int P(D) ~ dD = P_{t-1} * D_{t-1}^{-\frac{1}{\sigma}} * D_t^\frac{\sigma+1}{\sigma} * \frac{\sigma}{\sigma +1 }$

Consumer surplus = $ \left[ P_{t-1} * D_{t-1}^{-\frac{1}{\sigma}} * \frac{\sigma}{\sigma +1 } \right] \left[  D^{*~\frac{\sigma+1}{\sigma}} - (\tau * D^*)^ \frac{\sigma+1}{\sigma} \right] - (1- \tau)*D_t^* * P_t^*$

### Balance equation ###
PROD_forLocal (sl) + PROD_forExp (sa) + IMP (da) + sum_reg(reg_trade_in) = CONS_fromLocal (dl) + CONS_fromImp (da) + EXP (sa) + sum_reg(reg_trade_out)

(Note that this means that sl includes alread reg_trade_out, and dl includes already reg_trade_in)

In [23]:
# Computing 
gamma = 0.5
trs   = 0.1


# supplies and demands in Mm^3, prices in €/m^3
sigma =        productDataReg['value','sigma']
pc    =        productDataReg['value','pc']
pc_l  = lagged_productDataReg['value','pc']
sc    =        productDataReg['value','sc']*1000000
sc_l  = lagged_productDataReg['value','sc']*1000000
dc    =        productDataReg['value','dc']*1000000
dc_l  = lagged_productDataReg['value','dc']*1000000
inv   =        productDataReg['value','in']*1000000
inv_l = lagged_productDataReg['value','in']*1000000


productDataReg['value','surpl_pr']  =  (sc * pc) - \
                                      (pc_l /  pow(sc_l,1/sigma)) \
                                    * pow(inv_l/inv,gamma/sigma) \
                                    * pow(sc,(1+sigma)/sigma) \
                                    * (sigma / (1+sigma))

productDataReg['value','surpl_co']  =    (pc_l*pow(dc_l,-1/sigma)*sigma/(sigma+1)) \
                                      * (pow(dc,(sigma+1)/sigma)-pow(trs*dc,(sigma+1)/sigma)) \
                                      - (1-trs) * dc * pc
        
productDataReg['value','surpl_tot'] =  productDataReg.fillna(0)['value','surpl_pr']+ productDataReg.fillna(0)['value','surpl_co']        
        
productDataReg[90:110]

                                                   value                      \
parName                                               dl        da        dt
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.005935  0.008194  0.014129
                                          2096  0.005936  0.008194  0.014130
                                          2097  0.005937  0.008194  0.014131
                                          2098  0.005937  0.008194  0.014132
                                          2099  0.005938  0.008195  0.014132
                                          2100  0.005938  0.008195  0.014133
                                          2101  0.005938  0.008195  0.014133
                                          2102  0.005938  0.008195  0.014133
                                          2103  0.005938  0.008195  0.014134
                                          2104  0.005938  0.008195  0.014134
                                          2105  0.005939  0.008196  0.014134
                                          2106  0.005939  0.008196  0.014135
                                          2107  0.005939  0.008196  0.014135
                        ashRoundW primPr  2005  0.000303  0.000000  0.000303
                                          2006  0.000303  0.000000  0.000303
                                          2007  0.000534  0.000000  0.000534
                                          2008  0.000587  0.000000  0.000587
                                          2009  0.000646  0.000000  0.000646
                                          2010  0.000711  0.000000  0.000711
                                          2011  0.000782  0.000000  0.000782

                                                                              \
parName                                               dc        sl        sa
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.007402  0.000000  0.000000
                                          2096  0.007403  0.000000  0.000000
                                          2097  0.007403  0.000000  0.000000
                                          2098  0.007403  0.000000  0.000000
                                          2099  0.007404  0.000000  0.000000
                                          2100  0.007404  0.000000  0.000000
                                          2101  0.007404  0.000000  0.000000
                                          2102  0.007404  0.000000  0.000000
                                          2103  0.007404  0.000000  0.000000
                                          2104  0.007405  0.000000  0.000000
                                          2105  0.007405  0.000000  0.000000
                                          2106  0.007405  0.000000  0.000000
                                          2107  0.007405  0.000000  0.000000
                        ashRoundW primPr  2005  0.000000  0.012059  0.002225
                                          2006  0.000000  0.012059  0.002225
                                          2007  0.000000  0.011299  0.002398
                                          2008  0.000000  0.011272  0.002448
                                          2009  0.000000  0.011103  0.001911
                                          2010  0.000000  0.011044  0.002014
                                          2011  0.000000  0.011056  0.002271

                                                                              \
parName                                               st        sc        pl
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  0.000000  609.1190
                                          2096  0.000000  0.000000  609.0390
                                          2097  0.000000  0.000000  608.9810
                                          2098  0.000000  0.000000  608.9430
                                          2099  0.000000  0.000000  608.9200
                                          2100  0.000000  0.000000  608.9070
                                          2101  0.000000  0.000000  608.8990
                                          2102  0.000000  0.000000  608.8950
                                          2103  0.000000  0.000000  608.8910
                                          2104  0.000000  0.000000  608.8870
                                          2105  0.000000  0.000000  608.8820
                                          2106  0.000000  0.000000  608.8580
                                          2107  0.000000  0.000000  608.8250
                        ashRoundW primPr  2005  0.014284  0.005566   91.0000
                                          2006  0.014284  0.004627   91.0000
                                          2007  0.013697  0.004452   83.6508
                                          2008  0.013721  0.004464   82.0893
                                          2009  0.013014  0.004215   81.6309
                                          2010  0.013058  0.004230   79.7861
                                          2011  0.013326  0.004326   77.9309

                                                                             \
parName                                               pc        pw       in
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  1531.430  802.3210  0.00000
                                          2096  1531.360  802.2780  0.00000
                                          2097  1531.320  802.2460  0.00000
                                          2098  1531.290  802.2260  0.00000
                                          2099  1531.270  802.2140  0.00000
                                          2100  1531.260  802.2070  0.00000
                                          2101  1531.250  802.2020  0.00000
                                          2102  1531.250  802.2000  0.00000
                                          2103  1531.240  802.1980  0.00000
                                          2104  1531.240  802.1950  0.00000
                                          2105  1531.240  802.1930  0.00000
                                          2106  1531.220  802.1800  0.00000
                                          2107  1531.190  802.1620  0.00000
                        ashRoundW primPr  2005   229.151   92.0049  0.00000
                                          2006   284.018   92.0049  2.17569
                                          2007   270.467   87.9086  2.26469
                                          2008   267.196   86.9303  2.34426
                                          2009   251.145   81.3394  2.42514
                                          2010   248.375   80.4508  2.50787
                                          2011   249.666   81.0516  2.59147

                                                                \
parName                                            st_or sigma
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  -0.3
                                          2096  0.000000  -0.3
                                          2097  0.000000  -0.3
                                          2098  0.000000  -0.3
                                          2099  0.000000  -0.3
                                          2100  0.000000  -0.3
                                          2101  0.000000  -0.3
                                          2102  0.000000  -0.3
                                          2103  0.000000  -0.3
                                          2104  0.000000  -0.3
                                          2105  0.000000  -0.3
                                          2106  0.000000  -0.3
                                          2107  0.000000  -0.3
                        ashRoundW primPr  2005  0.000000   1.2
                                          2006  0.000000   1.2
                                          2007  0.013697   1.2
                                          2008  0.013721   1.2
                                          2009  0.013014   1.2
                                          2010  0.013058   1.2
                                          2011  0.013326   1.2

                                                                              \
parName                                               surpl_pr      surpl_co
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095             NaN  1.031434e+09
                                          2096             NaN  1.031471e+09
                                          2097             NaN  1.031518e+09
                                          2098             NaN  1.031585e+09
                                          2099             NaN  1.031626e+09
                                          2100             NaN  1.031656e+09
                                          2101             NaN  1.031688e+09
                                          2102             NaN  1.031710e+09
                                          2103             NaN  1.031737e+09
                                          2104             NaN  1.031765e+09
                                          2105             NaN  1.031779e+09
                                          2106             NaN  1.031761e+09
                                          2107             NaN  1.031768e+09
                        ashRoundW primPr  2005             NaN           NaN
                                          2006  1314236.491400           NaN
                                          2007   547327.458020           NaN
                                          2008   542149.125077           NaN
                                          2009   481163.209719           NaN
                                          2010   477509.198188           NaN
                                          2011   490970.445382           NaN


parName                                            surpl_tot
scen     country region prod      prodLev year
P0-Mi-Ei 11000   11010  ashPlyW   secPr   2095  1.031434e+09
                                          2096  1.031471e+09
                                          2097  1.031518e+09
                                          2098  1.031585e+09
                                          2099  1.031626e+09
                                          2100  1.031656e+09
                                          2101  1.031688e+09
                                          2102  1.031710e+09
                                          2103  1.031737e+09
                                          2104  1.031765e+09
                                          2105  1.031779e+09
                                          2106  1.031761e+09
                                          2107  1.031768e+09
                        ashRoundW primPr  2005  0.000000e+00
                                          2006  1.314236e+06
                                          2007  5.473275e+05
                                          2008  5.421491e+05
                                          2009  4.811632e+05
                                          2010  4.775092e+05
                                          2011  4.909704e+05

In [29]:
productDataReg_byprodLev = productDataReg.groupby(level=['scen','country','region','prodLev','year']).sum() # attenction, everything is just summed, prices are obviously not correct
productDataReg_byprodLev[:130]

#productDataReg['value']=999

#test
#print(productDataReg[:500])
#st_reg = productDataReg[productDataReg['parName']=='st']
#st_reg = st_reg.drop(['freeDim'],axis=1) 
#st_reg.rename(columns={'value':'st_value'}, inplace=True)
#st_reg.set_index(['scen','country','region','prod','year','parName'], inplace=True)
#result = pd.concat([productDataNat, st_reg], axis=1)
#productDataNat = productDataReg.drop(['freeDim'],axis=1)    # we don't want this in national data, but still keep it in regional one
#productDataNat = productDataNat[productDataNat['parName'] != 'rt'] # we don't want rt in national data
#productDataNat.set_index(['scen','country','region','prod','year','parName'], inplace=True)
#productDataNat[:5]

                                          value                       \
parName                                      dl        da         dt
scen     country region prodLev year
P0-Mi-Ei 11000   11010  primPr  2005   1.177444  0.000000   1.177444
                                2006   1.177444  0.000000   1.177444
                                2007   2.072304  0.000000   2.072304
                                2008   2.279538  0.000000   2.279538
                                2009   2.507488  0.000000   2.507488
                                2010   2.756074  0.000000   2.756074
                                2011   3.021258  0.000000   3.021258
                                2012   3.103704  0.000000   3.103704
                                2013   3.179758  0.000000   3.179758
                                2014   3.190169  0.000000   3.190169
                                2015   3.196658  0.000000   3.196658
                                2016   3.203185  0.000000   3.203185
                                2017   3.209888  0.000000   3.209888
                                2018   3.208590  0.000000   3.208590
                                2019   3.153060  0.000000   3.153060
                                2020   3.159527  0.000000   3.159527
                                2021   3.166259  0.000000   3.166259
                                2022   3.173299  0.000000   3.173299
                                2023   3.180579  0.000000   3.180579
                                2024   3.187757  0.000000   3.187757
                                2025   3.184899  0.000000   3.184899
                                2026   3.183531  0.000000   3.183531
                                2027   3.193019  0.000000   3.193019
                                2028   3.203112  0.000000   3.203112
                                2029   3.213418  0.000000   3.213418
                                2030   3.224453  0.000000   3.224453
                                2031   3.236661  0.000000   3.236661
                                2032   3.240777  0.000000   3.240777
                                2033   3.259108  0.000000   3.259108
                                2034   3.269644  0.000000   3.269644
...                                         ...       ...        ...
                                2105   3.691337  0.000000   3.691337
                                2106   3.697957  0.000000   3.697957
                                2107   3.704523  0.000000   3.704523
                        secPr   2005  11.564165  3.232008  14.796165
                                2006  11.564165  3.232008  14.796165
                                2007  10.374898  2.976182  13.351078
                                2008  10.436372  2.921751  13.358129
                                2009  10.272159  3.329893  13.602057
                                2010  10.437677  3.025176  13.462849
                                2011  10.499678  2.920586  13.420257
                                2012  10.404306  3.154624  13.558924
                                2013  10.443275  3.100023  13.543289
                                2014  10.470362  3.098329  13.568687
                                2015  10.497954  3.096737  13.594700
                                2016  10.524705  3.095248  13.619958
                                2017  10.550654  3.093870  13.644524
                                2018  10.573941  3.092544  13.666490
                                2019  10.583601  3.091309  13.674900
                                2020  10.607092  3.090219  13.697319
                                2021  10.629869  3.089224  13.719091
                                2022  10.651944  3.088311  13.740269
                                2023  10.673497  3.087395  13.760895
                                2024  10.694275  3.086620  13.780900
                                2025  10.711131  3.086139  13.797263
                                2026  10.727638  3.085708  13.813339
                                2027  10.746510  3.085172  13.831697
                                2028  10.764833  3.084715  13.849545
                                2029  10.782546  3.084310  13.866865
                                2030  10.799733  3.083974  13.883695
                                2031  10.832883  3.047713  13.880608

                                                                               \
parName                                      dc        sl        sa        st
scen     country region prodLev year
P0-Mi-Ei 11000   11010  primPr  2005   0.000000  0.570914  0.050049  0.620962
                                2006   0.000000  0.570914  0.050049  0.620962
                                2007   0.000000  0.760220  0.057418  0.817638
                                2008   0.000000  0.763492  0.059154  0.822646
                                2009   0.000000  0.772194  0.051315  0.823509
                                2010   0.000000  0.777707  0.050881  0.828586
                                2011   0.000000  0.786063  0.057201  0.843265
                                2012   0.000000  0.791829  0.043721  0.835551
                                2013   0.000000  0.797677  0.043717  0.841394
                                2014   0.000000  0.801155  0.044623  0.845778
                                2015   0.000000  0.804443  0.045547  0.849989
                                2016   0.000000  0.807633  0.046480  0.854113
                                2017   0.000000  0.810702  0.047421  0.858123
                                2018   0.000000  0.814232  0.048379  0.862611
                                2019   0.000000  0.821118  0.049379  0.870496
                                2020   0.000000  0.824001  0.050350  0.874350
                                2021   0.000000  0.826773  0.051328  0.878102
                                2022   0.000000  0.829472  0.052316  0.881787
                                2023   0.000000  0.832109  0.053313  0.885423
                                2024   0.000000  0.834703  0.054321  0.889024
                                2025   0.000000  0.837857  0.055343  0.893198
                                2026   0.000000  0.841928  0.056436  0.898365
                                2027   0.000000  0.846528  0.057608  0.904136
                                2028   0.000000  0.850900  0.058781  0.909682
                                2029   0.000000  0.853093  0.059837  0.912930
                                2030   0.000000  0.855196  0.060902  0.916097
                                2031   0.000000  0.857263  0.062820  0.920082
                                2032   0.000000  0.862721  0.064982  0.927703
                                2033   0.000000  0.874930  0.067679  0.942609
                                2034   0.000000  0.880111  0.069993  0.950103
...                                         ...       ...       ...       ...
                                2105   0.000000  0.897445  0.172502  1.069947
                                2106   0.000000  0.896854  0.172161  1.069015
                                2107   0.000000  0.896271  0.171816  1.068085
                        secPr   2005  11.160724  1.169315  0.000000  1.169315
                                2006  11.140913  1.169315  0.000000  1.169315
                                2007   9.886310  2.057996  0.000000  2.057996
                                2008   9.888385  2.263799  0.000000  2.263799
                                2009  10.046105  2.490175  0.000000  2.490175
                                2010   9.959826  2.738014  0.000000  2.738014
                                2011   9.930819  3.002360  0.000000  3.002360
                                2012  10.025796  3.083925  0.000000  3.083925
                                2013  10.013600  3.159065  0.000000  3.159065
                                2014  10.033128  3.168515  0.000000  3.168515
                                2015  10.053472  3.173959  0.000000  3.173959
                                2016  10.073223  3.179346  0.000000  3.179346
                                2017  10.092426  3.184807  0.000000  3.184807
                                2018  10.109177  3.182151  0.000000  3.182151
                                2019  10.112366  3.125136  0.000000  3.125136
                                2020  10.129857  3.129997  0.000000  3.129997
                                2021  10.146840  3.134951  0.000000  3.134951
                                2022  10.163338  3.140054  0.000000  3.140054
                                2023  10.179374  3.145212  0.000000  3.145212
                                2024  10.194845  3.150063  0.000000  3.150063
                                2025  10.207133  3.144648  0.000000  3.144648
                                2026  10.219202  3.140472  0.000000  3.140472
                                2027  10.233413  3.146880  0.000000  3.146880
                                2028  10.247236  3.153591  0.000000  3.153591
                                2029  10.260639  3.160183  0.000000  3.160183
                                2030  10.273658  3.167140  0.000000  3.167140
                                2031  10.271687  3.174851  0.000000  3.174851

                                                                      \
parName                                     sc         pl         pc
scen     country region prodLev year
P0-Mi-Ei 11000   11010  primPr  2005  0.188001   269.0000   862.3260
                                2006  0.157167   269.0000  1123.3770
                                2007  0.201942   279.2270  1259.9760
                                2008  0.202905   275.6837  1254.7640
                                2009  0.202306   282.5895  1266.2180
                                2010  0.203735   278.8969  1259.1570
                                2011  0.207142   275.3103  1264.3840
                                2012  0.205666   278.2515  1240.3340
                                2013  0.206951   276.0812  1230.6560
                                2014  0.207860   272.8723  1219.5560
                                2015  0.208746   269.9450  1209.3330
                                2016  0.209611   267.0953  1199.4980
                                2017  0.210446   264.3115  1190.0050
                                2018  0.211407   261.7518  1181.3540
                                2019  0.213215   259.9932  1175.5010
                                2020  0.214023   257.4635  1167.0200
                                2021  0.214803   254.9929  1158.8450
                                2022  0.215571   252.6003  1151.0080
                                2023  0.216329   250.2887  1143.4880
                                2024  0.217082   248.0481  1136.2360
                                2025  0.217976   245.9961  1129.8050
                                2026  0.219198   244.6266  1125.2630
                                2027  0.220667   243.9708  1122.5720
                                2028  0.222072   243.3500  1120.0650
                                2029  0.222749   241.5485  1114.5470
                                2030  0.223407   239.7443  1109.0810
                                2031  0.224276   237.7959  1106.2460
                                2032  0.226270   237.6086  1108.3290
                                2033  0.230644   241.5390  1121.1400
                                2034  0.232668   241.5148  1124.0540
...                                        ...        ...        ...
                                2105  0.276631   198.4045  1354.1450
                                2106  0.276202   198.3939  1354.2710
                                2107  0.275774   198.3879  1354.4080
                        secPr   2005  0.000000  2909.0000  5340.4872
                                2006  0.000000  2961.8000  5235.3688
                                2007  0.000000  2884.4461  5641.5103
                                2008  0.000000  2859.1580  5341.5100
                                2009  0.000000  2846.3411  4939.3810
                                2010  0.000000  2831.6572  4798.7032
                                2011  0.000000  2822.6843  4998.7444
                                2012  0.000000  2829.2179  5236.2554
                                2013  0.000000  2819.4056  5248.0676
                                2014  0.000000  2808.1493  5228.8889
                                2015  0.000000  2798.3815  5211.0146
                                2016  0.000000  2789.1128  5193.5624
                                2017  0.000000  2780.1586  5176.3678
                                2018  0.000000  2771.7276  5159.6938
                                2019  0.000000  2763.4157  5142.9655
                                2020  0.000000  2755.6093  5126.9160
                                2021  0.000000  2747.9034  5110.9740
                                2022  0.000000  2740.4448  5095.2895
                                2023  0.000000  2731.2447  5078.7826
                                2024  0.000000  2724.5580  5063.8131
                                2025  0.000000  2718.1268  5049.1547
                                2026  0.000000  2711.5994  5034.4711
                                2027  0.000000  2704.8672  5019.6304
                                2028  0.000000  2698.4725  5005.2402
                                2029  0.000000  2692.6822  4991.4915
                                2030  0.000000  2687.0778  4977.9227
                                2031  0.000000  2681.6234  5011.9378

                                                                            \
parName                                      pw         in     st_or sigma
scen     country region prodLev year
P0-Mi-Ei 11000   11010  primPr  2005   269.6426    0.00000  0.000000   4.2
                                2006   269.6426   60.64036  0.000000   4.2
                                2007   287.2603   62.57352  0.817638   4.2
                                2008   285.1308   64.21950  0.822646   4.2
                                2009   279.7854   65.87967  0.823509   4.2
                                2010   278.0579   67.55831  0.828586   4.2
                                2011   279.7853   69.24372  0.843265   4.2
                                2012   272.2530   70.91650  0.835551   4.2
                                2013   269.6880   72.61261  0.841394   4.2
                                2014   266.9094   74.30625  0.845778   4.2
                                2015   264.3947   75.99715  0.849989   4.2
                                2016   261.9649   77.68342  0.854113   4.2
                                2017   259.6100   79.36300  0.858123   4.2
                                2018   257.4726   81.03427  0.862611   4.2
                                2019   256.0794   82.69534  0.870496   4.2
                                2020   253.9928   84.33879  0.874350   4.2
                                2021   251.9743   85.96997  0.878102   4.2
                                2022   250.0398   87.58736  0.881787   4.2
                                2023   248.1913   89.18910  0.885423   4.2
                                2024   246.4195   90.77303  0.889024   4.2
                                2025   244.8334   92.33774  0.893198   4.2
                                2026   243.8348   93.88109  0.898365   4.2
                                2027   243.4395   95.40002  0.904136   4.2
                                2028   243.0844   96.89227  0.909682   4.2
                                2029   241.7515   98.35703  0.912930   4.2
                                2030   240.4313   99.79823  0.916097   4.2
                                2031   239.8006  101.21503  0.920082   4.2
                                2032   240.7207  102.60506  0.927703   4.2
                                2033   245.0905  103.96110  0.942609   4.2
                                2034   246.3056  105.26763  0.950103   4.2
...                                         ...        ...       ...   ...
                                2105   366.5619  129.15660  1.069947   4.2
                                2106   366.5891  129.00498  1.069015   4.2
                                2107   366.6149  128.85336  1.068085   4.2
                        secPr   2005  2908.4966    0.00000  0.000000  -3.6
                                2006  2908.4966    0.00000  0.000000  -3.6
                                2007  3122.8013    0.00000  2.057996  -3.6
                                2008  2958.2539    0.00000  2.263799  -3.6
                                2009  2745.3118    0.00000  2.490175  -3.6
                                2010  2657.1537    0.00000  2.738014  -3.6
                                2011  2766.7600    0.00000  3.002360  -3.6
                                2012  2909.1828    0.00000  3.083925  -3.6
                                2013  2913.9030    0.00000  3.159065  -3.6
                                2014  2902.9666    0.00000  3.168515  -3.6
                                2015  2892.7826    0.00000  3.173959  -3.6
                                2016  2882.8224    0.00000  3.179346  -3.6
                                2017  2873.0114    0.00000  3.184807  -3.6
                                2018  2863.5123    0.00000  3.182151  -3.6
                                2019  2854.1328    0.00000  3.125136  -3.6
                                2020  2844.9830    0.00000  3.129997  -3.6
                                2021  2835.8945    0.00000  3.134951  -3.6
                                2022  2826.9622    0.00000  3.140054  -3.6
                                2023  2817.6281    0.00000  3.145212  -3.6
                                2024  2809.0943    0.00000  3.150063  -3.6
                                2025  2800.7758    0.00000  3.144648  -3.6
                                2026  2792.4279    0.00000  3.140472  -3.6
                                2027  2783.9802    0.00000  3.146880  -3.6
                                2028  2775.7958    0.00000  3.153591  -3.6
                                2029  2768.0156    0.00000  3.160183  -3.6
                                2030  2760.3283    0.00000  3.167140  -3.6
                                2031  2777.3817    0.00000  3.174851  -3.6

                                                                     \
parName                                      surpl_pr      surpl_co
scen     country region prodLev year
P0-Mi-Ei 11000   11010  primPr  2005              NaN           NaN
                                2006  32503782.113730           NaN
                                2007  26396405.669381           NaN
                                2008  26332627.962193           NaN
                                2009  26042537.759215           NaN
                                2010  26082354.513152           NaN
                                2011  26612778.039710           NaN
                                2012  26025599.883088           NaN
                                2013  26075328.021147           NaN
                                2014  26020599.708660           NaN
                                2015  25962456.412442           NaN
                                2016  25906671.989217           NaN
                                2017  25851851.865059           NaN
                                2018  25834855.813561           NaN
                                2019  26039754.205603           NaN
                                2020  25997173.701222           NaN
                                2021  25955756.431001           NaN
                                2022  25917113.555886           NaN
                                2023  25882755.414940           NaN

## Saving dataframes to csv

In [32]:
productDataReg_byprodLev.to_csv("output/productDataReg_byprodLev.csv")