In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import sys          # only needed to determine Python version number

# Set some pandas parameters..
#pd.set_option('display.notebook_repr_html', True)
#pd.set_option('display.max_columns', 10)
#pd.set_option('display.max_rows', 10)

# Matplotlib ptions
import matplotlib.pyplot as plt
import matplotlib   # only needed to determine Matplotlib version number
# Render our plots inline:
%matplotlib inline  
pd.set_option('display.mpl_style', 'default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)

print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
#print('Matplotlib version ' + matplotlib.__version__)
#pd.show_versions()

Python version 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4]
Pandas version 0.17.1

In [2]:
#scenarios = ['P0-Mi-Ei'] # for quick testing
scenarios = ['P0-Mh-Ei', 'P1-Mh-Ei', 'P0-Mi-Ei', 'P1-Mi-Ei', 'P0-Me-Ei', 'P1-Me-Ei', 'P0-Mi-E0', 'P1-Mi-E0', 'P0-Mi-E1', 'P1-Mi-E1']
baseIDir = 'output/results'

productData_byscenario = [pd.read_csv(baseIDir+'/productData_'+scenario+'.csv',sep=';',  dtype={'value': np.float64}) for scenario in scenarios]
productDataReg = pd.concat(productData_byscenario)
productDataReg = productDataReg.drop(['Unnamed: 8'],axis=1) # we don't want this column never
#productDataReg['prodLev'] = np.where(productDataReg['prod'] in ['hardWRoundW', 'softWRoundW', 'pulpWFuelW'], 1, 2)
productDataReg['prodLev'] = np.where(productDataReg['prod'].isin(['hardWRoundW', 'softWRoundW', 'pulpWFuelW','ashRoundW']), 'primPr', 'secPr')
productDataReg = productDataReg.drop(['freeDim'],axis=1) # we don't want this column never
productDataReg = productDataReg[productDataReg['parName'] != 'rt'] # we don't want rt in national data
productDataReg.set_index(['scen','country','region','prod','prodLev','year','parName'], inplace=True)
productDataReg=productDataReg.unstack(['parName'])

lagged_productDataReg = productDataReg.groupby(level=['scen','country','region','prod','prodLev']).shift()




productDataReg[90:110]

                                                   value                      \
parName                                               dl        da        dt
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.005718  0.007879  0.013597
                                          2096  0.005718  0.007879  0.013597
                                          2097  0.005718  0.007879  0.013597
                                          2098  0.005718  0.007879  0.013597
                                          2099  0.005718  0.007879  0.013597
                                          2100  0.005718  0.007879  0.013597
                                          2101  0.005718  0.007879  0.013597
                                          2102  0.005719  0.007879  0.013597
                                          2103  0.005719  0.007879  0.013598
                                          2104  0.005719  0.007879  0.013598
                                          2105  0.005720  0.007878  0.013598
                                          2106  0.005719  0.007878  0.013598
                                          2107  0.005719  0.007878  0.013598
                        ashRoundW primPr  2005  0.000303  0.000000  0.000303
                                          2006  0.000303  0.000000  0.000303
                                          2007  0.000534  0.000000  0.000534
                                          2008  0.000587  0.000000  0.000587
                                          2009  0.000646  0.000000  0.000646
                                          2010  0.000711  0.000000  0.000711
                                          2011  0.000782  0.000000  0.000782

                                                                              \
parName                                               dc        sl        sa
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.007122  0.000000  0.000000
                                          2096  0.007122  0.000000  0.000000
                                          2097  0.007122  0.000000  0.000000
                                          2098  0.007122  0.000000  0.000000
                                          2099  0.007122  0.000000  0.000000
                                          2100  0.007122  0.000000  0.000000
                                          2101  0.007122  0.000000  0.000000
                                          2102  0.007122  0.000000  0.000000
                                          2103  0.007122  0.000000  0.000000
                                          2104  0.007122  0.000000  0.000000
                                          2105  0.007122  0.000000  0.000000
                                          2106  0.007122  0.000000  0.000000
                                          2107  0.007122  0.000000  0.000000
                        ashRoundW primPr  2005  0.000000  0.012059  0.002225
                                          2006  0.000000  0.012059  0.002225
                                          2007  0.000000  0.011260  0.002396
                                          2008  0.000000  0.011339  0.002453
                                          2009  0.000000  0.011180  0.001915
                                          2010  0.000000  0.011121  0.002019
                                          2011  0.000000  0.011095  0.002273

                                                                              \
parName                                               st        sc        pl
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  0.000000  607.8520
                                          2096  0.000000  0.000000  607.8310
                                          2097  0.000000  0.000000  607.8150
                                          2098  0.000000  0.000000  607.8020
                                          2099  0.000000  0.000000  607.7910
                                          2100  0.000000  0.000000  607.7820
                                          2101  0.000000  0.000000  607.7750
                                          2102  0.000000  0.000000  607.7580
                                          2103  0.000000  0.000000  607.7020
                                          2104  0.000000  0.000000  607.6480
                                          2105  0.000000  0.000000  607.6060
                                          2106  0.000000  0.000000  607.6120
                                          2107  0.000000  0.000000  607.6190
                        ashRoundW primPr  2005  0.014284  0.005566   91.0000
                                          2006  0.014284  0.004627   91.0000
                                          2007  0.013655  0.004439   83.3860
                                          2008  0.013792  0.004486   82.5308
                                          2009  0.013095  0.004241   82.1258
                                          2010  0.013140  0.004256   80.2828
                                          2011  0.013368  0.004340   78.1827

                                                                             \
parName                                               pc        pw       in
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  1530.410  801.6360  0.00000
                                          2096  1530.390  801.6250  0.00000
                                          2097  1530.380  801.6160  0.00000
                                          2098  1530.370  801.6090  0.00000
                                          2099  1530.360  801.6030  0.00000
                                          2100  1530.350  801.5980  0.00000
                                          2101  1530.350  801.5950  0.00000
                                          2102  1530.330  801.5850  0.00000
                                          2103  1530.290  801.5550  0.00000
                                          2104  1530.250  801.5260  0.00000
                                          2105  1530.210  801.5030  0.00000
                                          2106  1530.220  801.5060  0.00000
                                          2107  1530.220  801.5100  0.00000
                        ashRoundW primPr  2005   229.151   92.0049  0.00000
                                          2006   284.018   92.0049  2.17569
                                          2007   269.795   87.6987  2.26469
                                          2008   268.311   87.2773  2.34430
                                          2009   252.449   81.7630  2.42512
                                          2010   249.672   80.8686  2.50776
                                          2011   250.310   81.2543  2.59128


parName                                            st_or sigma
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  -0.3
                                          2096  0.000000  -0.3
                                          2097  0.000000  -0.3
                                          2098  0.000000  -0.3
                                          2099  0.000000  -0.3
                                          2100  0.000000  -0.3
                                          2101  0.000000  -0.3
                                          2102  0.000000  -0.3
                                          2103  0.000000  -0.3
                                          2104  0.000000  -0.3
                                          2105  0.000000  -0.3
                                          2106  0.000000  -0.3
                                          2107  0.000000  -0.3
                        ashRoundW primPr  2005  0.000000   1.2
                                          2006  0.000000   1.2
                                          2007  0.013655   1.2
                                          2008  0.013792   1.2
                                          2009  0.013095   1.2
                                          2010  0.013140   1.2
                                          2011  0.013368   1.2

## Computing producer and consumer surpluses ##

### Producer surplus ###
$ S_t = S_{t-1} P_{t-1}^{-\sigma} * {\left(  \frac{In_t}{In_{t-1}} \right)}^ {\frac{\gamma}{\sigma} } * P_{t}^{\sigma}  $

$ P_t = P _{t-1} * S_{t-1}^{-\frac{1}{\sigma}}* {\left(  \frac{In_{t-1}}{In_t} \right)}^ {\frac{\gamma}{\sigma} } * S_t^{\frac{1}{\sigma}} $

$ \int P(S) ~ dS = P _{t-1} * S_{t-1}^{-\frac{1}{\sigma}}* {\left(  \frac{In_{t-1}}{In_t} \right)}^ {\frac{\gamma}{\sigma} } * S_{t}^{\frac{\sigma+1}{\sigma}} *  \frac{\sigma}{\sigma+1} $

Producer surplus =  $ P^* * S^* - P _{t-1} * S_{t-1}^{-\frac{1}{\sigma}}* {\left(  \frac{In_{t-1}}{In_t} \right)}^ {\frac{\gamma}{\sigma} } * S^{* ~ \frac{\sigma+1}{\sigma}} *  \frac{\sigma}{\sigma+1}    $

### Consumer surplus ###

$ D_t = D_{t-1} * P_{t-1}^{-\sigma}*P_t^\sigma$

$P_t = P_{t-1} * D_{t-1}^{-\frac{1}{\sigma}} * D_t^\frac{1}{\sigma} $

$ \int P(D) ~ dD = P_{t-1} * D_{t-1}^{-\frac{1}{\sigma}} * D_t^\frac{\sigma+1}{\sigma} * \frac{\sigma}{\sigma +1 }$

Consumer surplus = $ \left[ P_{t-1} * D_{t-1}^{-\frac{1}{\sigma}} * \frac{\sigma}{\sigma +1 } \right] \left[  D^{*~\frac{\sigma+1}{\sigma}} - (\tau * D^*)^ \frac{\sigma+1}{\sigma} \right] - (1- \tau)*D_t^* * P_t^*$

### Balance equation ###
PROD_forLocal (sl) + PROD_forExp (sa) + IMP (da) + sum_reg(reg_trade_in) = CONS_fromLocal (dl) + CONS_fromImp (da) + EXP (sa) + sum_reg(reg_trade_out)

(Note that this means that sl includes alread reg_trade_out, and dl includes already reg_trade_in)

In [3]:
# Computing 
gamma = 0.5
trs   = 0.1


# supplies and demands in Mm^3, prices in €/m^3
sigma =        productDataReg['value','sigma']
pc    =        productDataReg['value','pc']
pc_l  = lagged_productDataReg['value','pc']
sc    =        productDataReg['value','sc']*1000000
sc_l  = lagged_productDataReg['value','sc']*1000000
dc    =        productDataReg['value','dc']*1000000
dc_l  = lagged_productDataReg['value','dc']*1000000
inv   =        productDataReg['value','in']*1000000
inv_l = lagged_productDataReg['value','in']*1000000


productDataReg['value','surpl_pr']  =  (sc * pc) - \
                                      (pc_l /  pow(sc_l,1/sigma)) \
                                    * pow(inv_l/inv,gamma/sigma) \
                                    * pow(sc,(1+sigma)/sigma) \
                                    * (sigma / (1+sigma))

productDataReg['value','surpl_co']  =    (pc_l*pow(dc_l,-1/sigma)*sigma/(sigma+1)) \
                                      * (pow(dc,(sigma+1)/sigma)-pow(trs*dc,(sigma+1)/sigma)) \
                                      - (1-trs) * dc * pc
        
productDataReg['value','surpl_tot'] =  productDataReg.fillna(0)['value','surpl_pr']+ productDataReg.fillna(0)['value','surpl_co']        
        
productDataReg[90:110]

                                                   value                      \
parName                                               dl        da        dt
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.005718  0.007879  0.013597
                                          2096  0.005718  0.007879  0.013597
                                          2097  0.005718  0.007879  0.013597
                                          2098  0.005718  0.007879  0.013597
                                          2099  0.005718  0.007879  0.013597
                                          2100  0.005718  0.007879  0.013597
                                          2101  0.005718  0.007879  0.013597
                                          2102  0.005719  0.007879  0.013597
                                          2103  0.005719  0.007879  0.013598
                                          2104  0.005719  0.007879  0.013598
                                          2105  0.005720  0.007878  0.013598
                                          2106  0.005719  0.007878  0.013598
                                          2107  0.005719  0.007878  0.013598
                        ashRoundW primPr  2005  0.000303  0.000000  0.000303
                                          2006  0.000303  0.000000  0.000303
                                          2007  0.000534  0.000000  0.000534
                                          2008  0.000587  0.000000  0.000587
                                          2009  0.000646  0.000000  0.000646
                                          2010  0.000711  0.000000  0.000711
                                          2011  0.000782  0.000000  0.000782

                                                                              \
parName                                               dc        sl        sa
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.007122  0.000000  0.000000
                                          2096  0.007122  0.000000  0.000000
                                          2097  0.007122  0.000000  0.000000
                                          2098  0.007122  0.000000  0.000000
                                          2099  0.007122  0.000000  0.000000
                                          2100  0.007122  0.000000  0.000000
                                          2101  0.007122  0.000000  0.000000
                                          2102  0.007122  0.000000  0.000000
                                          2103  0.007122  0.000000  0.000000
                                          2104  0.007122  0.000000  0.000000
                                          2105  0.007122  0.000000  0.000000
                                          2106  0.007122  0.000000  0.000000
                                          2107  0.007122  0.000000  0.000000
                        ashRoundW primPr  2005  0.000000  0.012059  0.002225
                                          2006  0.000000  0.012059  0.002225
                                          2007  0.000000  0.011260  0.002396
                                          2008  0.000000  0.011339  0.002453
                                          2009  0.000000  0.011180  0.001915
                                          2010  0.000000  0.011121  0.002019
                                          2011  0.000000  0.011095  0.002273

                                                                              \
parName                                               st        sc        pl
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  0.000000  607.8520
                                          2096  0.000000  0.000000  607.8310
                                          2097  0.000000  0.000000  607.8150
                                          2098  0.000000  0.000000  607.8020
                                          2099  0.000000  0.000000  607.7910
                                          2100  0.000000  0.000000  607.7820
                                          2101  0.000000  0.000000  607.7750
                                          2102  0.000000  0.000000  607.7580
                                          2103  0.000000  0.000000  607.7020
                                          2104  0.000000  0.000000  607.6480
                                          2105  0.000000  0.000000  607.6060
                                          2106  0.000000  0.000000  607.6120
                                          2107  0.000000  0.000000  607.6190
                        ashRoundW primPr  2005  0.014284  0.005566   91.0000
                                          2006  0.014284  0.004627   91.0000
                                          2007  0.013655  0.004439   83.3860
                                          2008  0.013792  0.004486   82.5308
                                          2009  0.013095  0.004241   82.1258
                                          2010  0.013140  0.004256   80.2828
                                          2011  0.013368  0.004340   78.1827

                                                                             \
parName                                               pc        pw       in
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  1530.410  801.6360  0.00000
                                          2096  1530.390  801.6250  0.00000
                                          2097  1530.380  801.6160  0.00000
                                          2098  1530.370  801.6090  0.00000
                                          2099  1530.360  801.6030  0.00000
                                          2100  1530.350  801.5980  0.00000
                                          2101  1530.350  801.5950  0.00000
                                          2102  1530.330  801.5850  0.00000
                                          2103  1530.290  801.5550  0.00000
                                          2104  1530.250  801.5260  0.00000
                                          2105  1530.210  801.5030  0.00000
                                          2106  1530.220  801.5060  0.00000
                                          2107  1530.220  801.5100  0.00000
                        ashRoundW primPr  2005   229.151   92.0049  0.00000
                                          2006   284.018   92.0049  2.17569
                                          2007   269.795   87.6987  2.26469
                                          2008   268.311   87.2773  2.34430
                                          2009   252.449   81.7630  2.42512
                                          2010   249.672   80.8686  2.50776
                                          2011   250.310   81.2543  2.59128

                                                                \
parName                                            st_or sigma
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  0.000000  -0.3
                                          2096  0.000000  -0.3
                                          2097  0.000000  -0.3
                                          2098  0.000000  -0.3
                                          2099  0.000000  -0.3
                                          2100  0.000000  -0.3
                                          2101  0.000000  -0.3
                                          2102  0.000000  -0.3
                                          2103  0.000000  -0.3
                                          2104  0.000000  -0.3
                                          2105  0.000000  -0.3
                                          2106  0.000000  -0.3
                                          2107  0.000000  -0.3
                        ashRoundW primPr  2005  0.000000   1.2
                                          2006  0.000000   1.2
                                          2007  0.013655   1.2
                                          2008  0.013792   1.2
                                          2009  0.013095   1.2
                                          2010  0.013140   1.2
                                          2011  0.013368   1.2

                                                                              \
parName                                               surpl_pr      surpl_co
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095             NaN  9.919296e+08
                                          2096             NaN  9.919161e+08
                                          2097             NaN  9.919138e+08
                                          2098             NaN  9.919054e+08
                                          2099             NaN  9.919050e+08
                                          2100             NaN  9.919000e+08
                                          2101             NaN  9.918948e+08
                                          2102             NaN  9.918930e+08
                                          2103             NaN  9.918698e+08
                                          2104             NaN  9.918522e+08
                                          2105             NaN  9.918379e+08
                                          2106             NaN  9.918384e+08
                                          2107             NaN  9.918436e+08
                        ashRoundW primPr  2005             NaN           NaN
                                          2006  1314236.491400           NaN
                                          2007   544340.169959           NaN
                                          2008   547144.748751           NaN
                                          2009   486676.697639           NaN
                                          2010   483000.636992           NaN
                                          2011   493743.460779           NaN


parName                                            surpl_tot
scen     country region prod      prodLev year
P0-Me-Ei 11000   11010  ashPlyW   secPr   2095  9.919296e+08
                                          2096  9.919161e+08
                                          2097  9.919138e+08
                                          2098  9.919054e+08
                                          2099  9.919050e+08
                                          2100  9.919000e+08
                                          2101  9.918948e+08
                                          2102  9.918930e+08
                                          2103  9.918698e+08
                                          2104  9.918522e+08
                                          2105  9.918379e+08
                                          2106  9.918384e+08
                                          2107  9.918436e+08
                        ashRoundW primPr  2005  0.000000e+00
                                          2006  1.314236e+06
                                          2007  5.443402e+05
                                          2008  5.471447e+05
                                          2009  4.866767e+05
                                          2010  4.830006e+05
                                          2011  4.937435e+05

In [4]:
productDataReg_byprodLev = productDataReg.groupby(level=['scen','country','region','prodLev','year']).sum() # attenction, everything is just summed, prices are obviously not correct
productDataReg_byprodLev[:130]

#productDataReg['value']=999

#test
#print(productDataReg[:500])
#st_reg = productDataReg[productDataReg['parName']=='st']
#st_reg = st_reg.drop(['freeDim'],axis=1) 
#st_reg.rename(columns={'value':'st_value'}, inplace=True)
#st_reg.set_index(['scen','country','region','prod','year','parName'], inplace=True)
#result = pd.concat([productDataNat, st_reg], axis=1)
#productDataNat = productDataReg.drop(['freeDim'],axis=1)    # we don't want this in national data, but still keep it in regional one
#productDataNat = productDataNat[productDataNat['parName'] != 'rt'] # we don't want rt in national data
#productDataNat.set_index(['scen','country','region','prod','year','parName'], inplace=True)
#productDataNat[:5]

                                          value                       \
parName                                      dl        da         dt
scen     country region prodLev year
P0-Me-Ei 11000   11010  primPr  2005   1.177444  0.000000   1.177444
                                2006   1.177444  0.000000   1.177444
                                2007   2.072304  0.000000   2.072304
                                2008   2.279538  0.000000   2.279538
                                2009   2.507488  0.000000   2.507488
                                2010   2.756074  0.000000   2.756074
                                2011   3.021288  0.000000   3.021288
                                2012   3.103714  0.000000   3.103714
                                2013   3.179768  0.000000   3.179768
                                2014   3.190159  0.000000   3.190159
                                2015   3.196638  0.000000   3.196638
                                2016   3.203155  0.000000   3.203155
                                2017   3.209848  0.000000   3.209848
                                2018   3.208600  0.000000   3.208600
                                2019   3.153010  0.000000   3.153010
                                2020   3.159477  0.000000   3.159477
                                2021   3.166179  0.000000   3.166179
                                2022   3.173169  0.000000   3.173169
                                2023   3.180419  0.000000   3.180419
                                2024   3.187717  0.000000   3.187717
                                2025   3.184859  0.000000   3.184859
                                2026   3.183371  0.000000   3.183371
                                2027   3.192849  0.000000   3.192849
                                2028   3.202942  0.000000   3.202942
                                2029   3.213278  0.000000   3.213278
                                2030   3.224314  0.000000   3.224314
                                2031   3.236552  0.000000   3.236552
                                2032   3.240777  0.000000   3.240777
                                2033   3.259108  0.000000   3.259108
                                2034   3.269693  0.000000   3.269693
...                                         ...       ...        ...
                                2105   3.691224  0.000000   3.691224
                                2106   3.697871  0.000000   3.697871
                                2107   3.704465  0.000000   3.704465
                        secPr   2005  11.564165  3.232008  14.796165
                                2006  11.564165  3.232008  14.796165
                                2007  10.374879  2.976229  13.351109
                                2008  10.436689  2.921773  13.358464
                                2009  10.272546  3.329898  13.602442
                                2010  10.438047  3.025161  13.463216
                                2011  10.500003  2.920545  13.420548
                                2012  10.404578  3.154567  13.559137
                                2013  10.443490  3.099941  13.543421
                                2014  10.470532  3.098237  13.568767
                                2015  10.498092  3.096619  13.594720
                                2016  10.524809  3.095113  13.619935
                                2017  10.550721  3.093722  13.644438
                                2018  10.574002  3.092382  13.666376
                                2019  10.583598  3.091137  13.674741
                                2020  10.607077  3.090036  13.697109
                                2021  10.629821  3.089031  13.718848
                                2022  10.651872  3.088110  13.739973
                                2023  10.673402  3.087197  13.760591
                                2024  10.694201  3.086403  13.780593
                                2025  10.711030  3.085915  13.796941
                                2026  10.727486  3.085477  13.812975
                                2027  10.746352  3.084947  13.831283
                                2028  10.764649  3.084475  13.849132
                                2029  10.782374  3.084068  13.866451
                                2030  10.799559  3.083725  13.883274
                                2031  10.832705  3.047472  13.880161

                                                                               \
parName                                      dc        sl        sa        st
scen     country region prodLev year
P0-Me-Ei 11000   11010  primPr  2005   0.000000  0.570914  0.050049  0.620962
                                2006   0.000000  0.570914  0.050049  0.620962
                                2007   0.000000  0.760182  0.057416  0.817599
                                2008   0.000000  0.763553  0.059159  0.822712
                                2009   0.000000  0.772263  0.051319  0.823582
                                2010   0.000000  0.777774  0.050885  0.828658
                                2011   0.000000  0.786095  0.057204  0.843299
                                2012   0.000000  0.791841  0.043722  0.835563
                                2013   0.000000  0.797673  0.043716  0.841388
                                2014   0.000000  0.801136  0.044622  0.845757
                                2015   0.000000  0.804412  0.045545  0.849959
                                2016   0.000000  0.807593  0.046478  0.854071
                                2017   0.000000  0.810654  0.047418  0.858073
                                2018   0.000000  0.814173  0.048376  0.862549
                                2019   0.000000  0.821054  0.049375  0.870430
                                2020   0.000000  0.823934  0.050346  0.874279
                                2021   0.000000  0.826709  0.051324  0.878033
                                2022   0.000000  0.829417  0.052312  0.881728
                                2023   0.000000  0.832063  0.053310  0.885373
                                2024   0.000000  0.834649  0.054317  0.888966
                                2025   0.000000  0.837799  0.055339  0.893137
                                2026   0.000000  0.841880  0.056433  0.898313
                                2027   0.000000  0.846480  0.057604  0.904085
                                2028   0.000000  0.850851  0.058778  0.909629
                                2029   0.000000  0.853027  0.059833  0.912860
                                2030   0.000000  0.855127  0.060896  0.916023
                                2031   0.000000  0.857185  0.062814  0.919999
                                2032   0.000000  0.862626  0.064976  0.927602
                                2033   0.000000  0.874822  0.067671  0.942493
                                2034   0.000000  0.880000  0.069985  0.949985
...                                         ...       ...       ...       ...
                                2105   0.000000  0.897372  0.172506  1.069878
                                2106   0.000000  0.896788  0.172164  1.068952
                                2107   0.000000  0.896213  0.171819  1.068031
                        secPr   2005  11.160724  1.169315  0.000000  1.169315
                                2006  11.140913  1.169315  0.000000  1.169315
                                2007   9.886348  2.057996  0.000000  2.057996
                                2008   9.888613  2.263799  0.000000  2.263799
                                2009  10.046355  2.490175  0.000000  2.490175
                                2010   9.960065  2.738014  0.000000  2.738014
                                2011   9.931007  3.002390  0.000000  3.002390
                                2012  10.025941  3.083935  0.000000  3.083935
                                2013  10.013699  3.159075  0.000000  3.159075
                                2014  10.033185  3.168505  0.000000  3.168505
                                2015  10.053489  3.173939  0.000000  3.173939
                                2016  10.073196  3.179316  0.000000  3.179316
                                2017  10.092373  3.184767  0.000000  3.184767
                                2018  10.109111  3.182161  0.000000  3.182161
                                2019  10.112259  3.125086  0.000000  3.125086
                                2020  10.129741  3.129937  0.000000  3.129937
                                2021  10.146697  3.134871  0.000000  3.134871
                                2022  10.163154  3.139924  0.000000  3.139924
                                2023  10.179184  3.145052  0.000000  3.145052
                                2024  10.194671  3.150023  0.000000  3.150023
                                2025  10.206946  3.144608  0.000000  3.144608
                                2026  10.218960  3.140312  0.000000  3.140312
                                2027  10.233170  3.146710  0.000000  3.146710
                                2028  10.246979  3.153421  0.000000  3.153421
                                2029  10.260381  3.160043  0.000000  3.160043
                                2030  10.273398  3.167000  0.000000  3.167000
                                2031  10.271433  3.174741  0.000000  3.174741

                                                                      \
parName                                     sc         pl         pc
scen     country region prodLev year
P0-Me-Ei 11000   11010  primPr  2005  0.188001   269.0000   862.3260
                                2006  0.157167   269.0000  1123.3770
                                2007  0.201930   278.9642  1259.3050
                                2008  0.202925   276.1245  1255.8760
                                2009  0.202330   283.0815  1267.5140
                                2010  0.203759   279.3905  1260.4420
                                2011  0.207153   275.5595  1265.0210
                                2012  0.205670   278.3620  1240.6300
                                2013  0.206948   276.0724  1230.6320
                                2014  0.207853   272.7704  1219.2840
                                2015  0.208734   269.7674  1208.8600
                                2016  0.209596   266.8548  1198.8560
                                2017  0.210429   264.0167  1189.2210
                                2018  0.211386   261.4091  1180.4450
                                2019  0.213192   259.6026  1174.4670
                                2020  0.213999   257.0422  1165.9060
                                2021  0.214781   254.5821  1157.7610
                                2022  0.215551   252.2297  1150.0330
                                2023  0.216312   249.9565  1142.6170
                                2024  0.217063   247.7118  1135.3550
                                2025  0.217956   245.6424  1128.8800
                                2026  0.219180   244.2907  1124.3880
                                2027  0.220649   243.6380  1121.7080
                                2028  0.222053   242.9957  1119.1460
                                2029  0.222725   241.1187  1113.4350
                                2030  0.223382   239.2931  1107.9160
                                2031  0.224248   237.3002  1104.9740
                                2032  0.226237   237.0522  1106.9110
                                2033  0.230607   240.9104  1119.5510
                                2034  0.232629   240.8834  1122.4700
...                                        ...        ...        ...
                                2105  0.276623   197.7009  1353.0870
                                2106  0.276197   197.7225  1353.2620
                                2107  0.275770   197.7474  1353.4450
                        secPr   2005  0.000000  2909.0000  5340.4872
                                2006  0.000000  2961.8000  5235.3688
                                2007  0.000000  2884.8701  5648.9703
                                2008  0.000000  2856.1460  5342.6620
                                2009  0.000000  2843.8493  4938.4042
                                2010  0.000000  2830.1052  4797.7642
                                2011  0.000000  2818.3739  4995.8020
                                2012  0.000000  2822.8558  5231.8082
                                2013  0.000000  2814.4247  5244.3188
                                2014  0.000000  2803.8046  5225.4022
                                2015  0.000000  2794.4810  5207.7471
                                2016  0.000000  2785.4304  5190.3760
                                2017  0.000000  2776.6113  5173.2645
                                2018  0.000000  2768.2161  5156.5723
                                2019  0.000000  2760.0197  5139.9545
                                2020  0.000000  2752.1223  5123.8100
                                2021  0.000000  2744.3125  5107.8702
                                2022  0.000000  2736.6891  5092.1848
                                2023  0.000000  2728.0161  5076.0680
                                2024  0.000000  2720.9937  5060.9098
                                2025  0.000000  2714.3786  5046.1585
                                2026  0.000000  2707.7587  5031.5145
                                2027  0.000000  2701.0376  5016.8128
                                2028  0.000000  2694.7149  5002.5477
                                2029  0.000000  2688.9506  4988.7189
                                2030  0.000000  2683.3672  4975.0822
                                2031  0.000000  2677.6887  5008.9192

                                                                            \
parName                                      pw         in     st_or sigma
scen     country region prodLev year
P0-Me-Ei 11000   11010  primPr  2005   269.6426    0.00000  0.000000   4.2
                                2006   269.6426   60.64036  0.000000   4.2
                                2007   287.0518   62.57352  0.817599   4.2
                                2008   285.4772   64.21954  0.822712   4.2
                                2009   280.2066   65.87965  0.823582   4.2
                                2010   278.4730   67.55810  0.828658   4.2
                                2011   279.9859   69.24343  0.843299   4.2
                                2012   272.3508   70.91617  0.835563   4.2
                                2013   269.6804   72.61226  0.841388   4.2
                                2014   266.8194   74.30581  0.845757   4.2
                                2015   264.2379   75.99683  0.849959   4.2
                                2016   261.7534   77.68304  0.854071   4.2
                                2017   259.3521   79.36264  0.858073   4.2
                                2018   257.1738   81.03406  0.862549   4.2
                                2019   255.7401   82.69520  0.870430   4.2
                                2020   253.6282   84.33881  0.874279   4.2
                                2021   251.6205   85.97017  0.878033   4.2
                                2022   249.7223   87.58773  0.881728   4.2
                                2023   247.9080   89.18954  0.885373   4.2
                                2024   246.1340   90.77364  0.888966   4.2
                                2025   244.5344   92.33842  0.893137   4.2
                                2026   243.5525   93.88193  0.898313   4.2
                                2027   243.1612   95.40102  0.904085   4.2
                                2028   242.7895   96.89324  0.909629   4.2
                                2029   241.3956   98.35827  0.912860   4.2
                                2030   240.0597   99.79956  0.916023   4.2
                                2031   239.3977  101.21654  0.919999   4.2
                                2032   240.2751  102.60687  0.927602   4.2
                                2033   244.5952  103.96293  0.942493   4.2
                                2034   245.8165  105.26978  0.949985   4.2
...                                         ...        ...       ...   ...
                                2105   366.6706  129.17437  1.069878   4.2
                                2106   366.6928  129.02278  1.068952   4.2
                                2107   366.7136  128.87108  1.068031   4.2
                        secPr   2005  2908.4966    0.00000  0.000000  -3.6
                                2006  2908.4966    0.00000  0.000000  -3.6
                                2007  3128.1373    0.00000  2.057996  -3.6
                                2008  2959.5830    0.00000  2.263799  -3.6
                                2009  2744.9740    0.00000  2.490175  -3.6
                                2010  2656.7027    0.00000  2.738014  -3.6
                                2011  2765.2306    0.00000  3.002390  -3.6
                                2012  2906.7657    0.00000  3.083935  -3.6
                                2013  2911.8071    0.00000  3.159075  -3.6
                                2014  2900.9869    0.00000  3.168505  -3.6
                                2015  2890.8941    0.00000  3.173939  -3.6
                                2016  2880.9710    0.00000  3.179316  -3.6
                                2017  2871.1921    0.00000  3.184767  -3.6
                                2018  2861.6899    0.00000  3.182161  -3.6
                                2019  2852.3688    0.00000  3.125086  -3.6
                                2020  2843.1620    0.00000  3.129937  -3.6
                                2021  2834.0847    0.00000  3.134871  -3.6
                                2022  2825.1755    0.00000  3.139924  -3.6
                                2023  2816.0556    0.00000  3.145052  -3.6
                                2024  2807.4391    0.00000  3.150023  -3.6
                                2025  2799.0716    0.00000  3.144608  -3.6
                                2026  2790.7623    0.00000  3.140312  -3.6
                                2027  2782.4156    0.00000  3.146710  -3.6
                                2028  2774.3242    0.00000  3.153421  -3.6
                                2029  2766.4770    0.00000  3.160043  -3.6
                                2030  2758.7427    0.00000  3.167000  -3.6
                                2031  2775.6851    0.00000  3.174741  -3.6

                                                                     \
parName                                      surpl_pr      surpl_co
scen     country region prodLev year
P0-Me-Ei 11000   11010  primPr  2005              NaN           NaN
                                2006  32503782.113730           NaN
                                2007  26393519.488008           NaN
                                2008  26337225.257330           NaN
                                2009  26047474.351692           NaN
                                2010  26087154.929695           NaN
                                2011  26615267.342399           NaN
                                2012  26026399.399694           NaN
                                2013  26074994.280544           NaN
                                2014  26019358.385564           NaN
                                2015  25960488.089708           NaN
                                2016  25903986.766720           NaN
                                2017  25848766.977308           NaN
                                2018  25831203.261354           NaN
                                2019  26035855.212971           NaN
                                2020  25992941.061631           NaN
                                2021  25951781.819272           NaN
                                2022  25913887.913158           NaN
                                2023  25880069.283212           NaN

## Saving dataframes to csv

In [36]:
productDataReg_byprodLev.to_csv("output/productDataReg_byprodLev.csv")

In [5]:
h5 = pd.HDFStore('output/test.h5')
h5['productDataReg'] = productDataReg
h5.close()

#h5bis = pd.HDFStore('output/test.h5')
#test = h5bis['productDataReg'] 
#test.head()